CREATE DATABASE IF NOT EXISTS EMPRESA;

USE EMPRESA;

CREATE TABLE IF NOT EXISTS FUNCIONARIO
(Pnome VARCHAR(15) NOT NULL,
Minicial CHAR,
Unome VARCHAR(15) NOT NULL,
Cpf CHAR(11) NOT NULL,
Datanasc DATE,
Endereco VARCHAR(100),
Sexo CHAR,
Salario DECIMAL(10,2),
Cpf_supervisor CHAR(11) NULL,
Dnr INT,
PRIMARY KEY (Cpf),
FOREIGN KEY (Cpf_supervisor) REFERENCES FUNCIONARIO(Cpf)

);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO
( Dnome VARCHAR(15) NOT NULL,
Dnumero INT NOT NULL,
Cpf_gerente CHAR(11) NULL,
Data_inicio_gerente DATE,
PRIMARY KEY (Dnumero),
UNIQUE (Dnome),
FOREIGN KEY (Cpf_gerente) REFERENCES FUNCIONARIO(Cpf));

ALTER TABLE FUNCIONARIO
ADD FOREIGN KEY (Dnr) REFERENCES DEPARTAMENTO(Dnumero);

CREATE TABLE IF NOT EXISTS LOCALIZACAO_DEP
( Dnumero INT NOT NULL,
Dlocal VARCHAR(15) NOT NULL,
PRIMARY KEY (Dnumero, Dlocal),
FOREIGN KEY (Dnumero) REFERENCES DEPARTAMENTO(Dnumero) 
);

CREATE TABLE IF NOT EXISTS PROJETO
(Projnome VARCHAR(15) NOT NULL,
Projnumero INT NOT NULL,
Projlocal VARCHAR(15),
Dnum INT NOT NULL,
PRIMARY KEY (Projnumero),
UNIQUE (Projnome),
FOREIGN KEY (Dnum) REFERENCES DEPARTAMENTO(Dnumero) 
);

CREATE TABLE IF NOT EXISTS TRABALHA_EM
( Fcpf CHAR(11) NOT NULL,
Pnr INT NOT NULL,
Horas DECIMAL(3,1) NULL,
PRIMARY KEY (Fcpf, Pnr),
FOREIGN KEY (Fcpf) REFERENCES FUNCIONARIO(Cpf),
FOREIGN KEY (Pnr) REFERENCES PROJETO(Projnumero) 
);

CREATE TABLE IF NOT EXISTS DEPENDENTE
( Fcpf CHAR(11) NOT NULL,
Nome_dependente VARCHAR(15) NOT NULL,
Sexo CHAR,
Datanasc DATE,
Parentesco VARCHAR(8),
PRIMARY KEY (Fcpf, Nome_dependente),
FOREIGN KEY (Fcpf) REFERENCES FUNCIONARIO(Cpf) 
);
